openapi: 3.0.3
info:
  title: Contact
  version: 0.0.1
tags:
  - name: Contact
    description: User contact API
servers:
  - url: http://localhost
  - url: http://192.168.1.116
  - url: https://geduardo.com
paths:
  /api/contact/contact:
    get:
      summary: Get user contacts
      operationId: handle_get_user_contacts
      tags:
        - Contact
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/'
        '404':
          $ref: '../common/openapi.yml#/components/responses/NotFound'
        '401':
          $ref: '../common/openapi.yml#/components/responses/Unauthorized'
        '500':
          $ref: '../common/openapi.yml#/components/responses/InternalServerError'

components:
  responses:
    ResponseUserJson:
      description: Successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/UserJson'
              error:
                type: object
                nullable: true
                example: null
                
  schemas:
    UserJson:
      type: object
      properties:
        firstname:
          type: string
          pattern: '^[a-zA-Z\s]{1,50}$'
          example: 'Pepe'
        lastname:
          type: string
          pattern: '^[a-zA-Z\s]{1,50}$'
          example: 'Garcia'
        nationality:
          type: string
          description: 'Nationality should be alpha-3 code (ISO 3166)'
          pattern: '^[A-Z]{3}$'
          example: 'MEX'
        birthday:
          type: string
          format: date
          description: 'You must be at least 13 years old'
          example: '2000-01-01'
        languages:
          type: array
          items:
            type: string
            description: 'Language should be alpha-2 code (ISO 639-1)'
            pattern: '^[A-Z]{2}$'
            example: 'ES'

    ContactsJson:
      type: object
      properties:
        contacts:
          type: array
          items:
            type: object
            properties:
              alias:
                type: string
                example: 'Pepe'
              firstname:
                type: string
                example: 'Pepe Garcia'
              identifier:
                type: string
                example: 'pepe@some.com'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
