# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/adapter/driven/persistence/pgsql/schema.rs"

[migrations_directory]
dir = "src/adapter/driven/persistence/pgsql/migrations"
