[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
toml = "0.7.1"
serde = "1.0.152"
serde_json = "1.0"
argon2 = "0.5.0"
rand_core = { version = "0.6", features = ["std"] }
jsonwebtoken = "8.3.0"
dotenvy = "0.15"
dotenv = "0.15.0"
serde_with = "3.0.0"
async-trait = "0.1.71"
