openapi: 3.0.3
info:
  title: Common
  version: 0.0.1
paths:
  /common:
    get:
      summary: Common Module
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Common Module
components:
  responses:
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '../../common/docs/openapi.yml#/components/schemas/ResponseErrorJson'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '../../common/docs/openapi.yml#/components/schemas/ResponseErrorJson'
    
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '../../common/docs/openapi.yml#/components/schemas/ResponseErrorJson'
  
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '../../common/docs/openapi.yml#/components/schemas/ResponseErrorJson'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '../../common/docs/openapi.yml#/components/schemas/ResponseErrorJson'

  schemas:
    ResponseErrorJson:
      type: object
      properties:
        data:
          type: object
          nullable: true
          example: null
        error:
          type: object
          properties:
            code:
              type: number
            message:
              type: string
            details:
              type: string
  
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: Profile
    description: User profile API
