openapi: 3.0.3
info:
  title: Profile
  version: 0.0.1
paths:
  /api/profile:
    get:
      summary: Get user information
      tags:
        - Profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUserJson'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
    put:
      summary: Update user information
      tags:
        - Profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserJson'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUserJson'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
          
components:
  responses:

    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '../../common/docs/openapi.yml#/components/schemas/ResponseErrorJson'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '../../common/docs/openapi.yml#/components/schemas/ResponseErrorJson'
    
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '../../common/docs/openapi.yml#/components/schemas/ResponseErrorJson'
  
  schemas:

    UserJson:
      type: object
      properties:
        firstname:
          type: string
          pattern: '^[a-zA-Z\s]{1,50}$'
        lastname:
          type: string
          pattern: '^[a-zA-Z\s]{1,50}$'
        nationality:
          $ref: '../../common/docs/openapi.yml#/components/schemas/Nationality'
        birthday:
          type: string
          format: date
        languages:
          type: array
          items:
            $ref: '../../common/docs/openapi.yml#/components/schemas/Language'

    ResponseUserJson:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/UserJson'
        error:
          type: object
          nullable: true
          example: null

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: Profile
    description: User profile API
