[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features=["json"]}
rocket_sync_db_pools = { version = "0.1.0-rc.2", features = ["diesel_postgres_pool"] }
toml = "0.7.1"
serde = "1.0.152"
diesel = { version = "2.0.0", features = ["postgres", "uuid", "chrono"] }
dotenvy = "0.15"